TRAIN_DIR="yt8m_train_local/all/gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe" 
MODEL_NAME=NetVLADModelLF
gcloud --verbosity=debug ml-engine local train --package-path=youtube-8m \
                                               --module-name=youtube-8m.train \
                                               -- --train_data_pattern='gs://youtube8m-ml-us-east1/2/frame/train/train*.tfrecord' \
                                               --frame_features=True \
                                               --model=$MODEL_NAME \
                                               --train_dir=$TRAIN_DIR  \
                                               --feature_names="rgb,audio" \
                                               --feature_sizes="1024,128" \
                                               --batch_size=80 \
                                               --base_learning_rate=0.0002 \
                                               --learning_rate_decay=0.8 \
                                               --netvlad_cluster_size=256 \
                                               --netvlad_hidden_size=1024 \
                                               --moe_l2=1e-6 \
                                               --iterations=300 \
                                               --netvlad_relu=False \
                                               --gating=True \
                                               --moe_prob_gating=True \
                                               --num_readers=4 \
                                               --num_epochs=5 \
